HEADER = """
DATE/TIME  : 05 Aug 2014 11:36
OPERATOR  : CHANGEME
FILENAME  : conv-CHANGEME.cal
COMMENTS1  : 150kHz - 230MHz nnV
COMMENTS2  :
COMMENTS3  : Generated by CIS9942_to_H_Immunity.py
RF GENERATOR GPIB/NAME  : 19 Hewlett Packard 8648B
Frequency Range in MHz  :  0.009   2000
Amplitude Range in dBm  : -136   13
AMPLIFIER NAME  : MANUAL
Frequency Range in MHz  :  0.01   2400
Gain  :  40
POWER METER/ANALYSER GPIB/NAME  : 17 HP 437B
Frequency Range in MHz  :  0.1   50000
Amplitude Range in dBm  : -70   44
Linearity File  : unknown.pml
Forward Probe Factor  : unknown.pmp
Reverse Probe Factor  : unknown.pmp
VOLTMETER GPIB/NAME  : 08 Rohde and Schwarz NRVS
Volt Meter Factor : None NONE.ANC
CURRENT PROBE MONITOR GPIB/NAME  : 20 HP 8591EM (ZERO ATTEN)
Current Probe Factor : LPE280  lpe280v1.anc
TRANSDUCER TYPE  : CDN 20db_att.ext
CALIBRATION TYPE  : normal 0
FREQUENCY START/STOP  : 0.150 230.000
FREQUENCY INCREMENT  :  1 log
VOLT LEVEL MIN/MAX  :  18   19
VOLT GRAPH SCALE MIN/MAX  :  0  20
IMAX CURRENT LIMIT   : 0 1 NONE.IMX
EQUIPMENT WAIT TIME  :  0
POWER METER USED : yes
POWER METER ZEROING  : manual
POWER METER ATTEMPTS  : 10
POWER METER TOLERANCE  :  1  -1
RF GENERATOR MODULATION  : off AM  80  EUT  1000   1   1
RF GENERATOR SAFETY MAX LIMIT  : 0_dbm.asl 0_DBM.ASL 0_DBM.ASL
RF GENERATOR FIXED LEVEL  :  0
PROFILE NAME/TOLERANCES USED  : NO  0.5   0  61000-4-6_10v_150k-100m.pfl
AMPLIFIER BREAKPOINTS  :  0   0
REVERSE POWER : no
 1
40db.bdc
01,  0 , 0 ,
02,  0 , 0 ,
03,  0 , 0 ,
04,  0 , 0 ,
05,  0 , 0 ,
06,  0 , 0 ,
07,  0 , 0 ,
08,  0 , 0 ,
09,  0 , 0 ,
10,  0 , 0 ,
11,  0 , 0 ,
12,  0 , 0 ,
13,  0 , 0 ,
14,  0 , 0 ,
15,  0 , 0 ,
#Freq(MHz) F Strength(V/m) Sig Gen(dBm) Power Fwd(dBm) Rev(dBm) Nett(dBm)
"""

'''
Freq(MHz) F Strength(V/m) Sig Gen(dBm) Power Fwd(dBm) Rev(dBm) Nett(dBm)
TARGET 0.150000,18.542,-15.9,35.21,999.000,999.000

SRC 150.000 kHz 	 10.250 	 10.418 	 -21.0 	 29.890
'''
